name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Go версии 1.23.4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: go mod tidy

    # Шаг 4: Запуск тестов
    - name: Run tests
      run: go test -v ./...

    # Шаг 5: Деплой (пример для SSH)
    - name: Deploy to server
      if: success()  # Выполняется только при успешном выполнении предыдущих шагов
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /path/to/project
        git pull origin main
        go build -o myapp
        ./myapp &
        EOF
