name: SSH Setup and Deploy to Server

on:
  push:
    branches:
      - main  # или другая ветка, для которой нужно выполнить деплой

jobs:
  setup-ssh-and-deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu для работы с SSH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "Starting SSH setup..."
          
          # Создаем папку для SSH, если ее нет
          mkdir -p ~/.ssh
          
          # Проверим, что папка существует
          ls -la ~/.ssh  
          
          # Запишем приватный ключ в файл (из секрета)
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          
          # Проверим, что файл id_rsa появился
          ls -la ~/.ssh  
          
          # Устанавливаем правильные права доступа на ключ
          chmod 600 ~/.ssh/id_rsa
          
          # Проверим права на id_rsa
          ls -la ~/.ssh
          
          # Проверим содержимое приватного ключа (чтобы убедиться, что он правильно записан)
          cat ~/.ssh/id_rsa  
          
          # Сканируем и добавляем хост в known_hosts, чтобы избежать предупреждения о неизвестном хосте
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts
          
          # Проверим, что хост добавлен в known_hosts
          cat ~/.ssh/known_hosts

          echo "SSH setup completed"

      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection..."
          
          # Подключаемся к серверу и выполняем тестовую команду
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kawabanga@192.168.0.13 "echo 'SSH connection successful'"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          echo "Starting deployment to the server..."
          
          # Пример: Копирование файлов на сервер (например, через SCP)
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./path/to/your/app kawabanga@192.168.0.13:/path/to/remote/deploy/directory

          # Пример: Выполнение команды на сервере для перезапуска приложения
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no kawabanga@192.168.0.13 << EOF
            cd /path/to/remote/deploy/directory
            # Выполним команды для развертывания, например, перезапуск сервиса или сборка
            git pull origin main  # Например, если проект на сервере в git репозитории
            docker-compose up -d  # Если используешь Docker
            # Другие команды для деплоя
          EOF

          echo "Deployment completed"

      - name: SSH Success Message
        run: echo "Deployment was successful!"
