name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Передача секрета в переменную окружения

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up SSH
        run: |
          echo "Starting SSH setup..."
          
          # Проверим, что переменная SSH_PRIVATE_KEY передана
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "ERROR: SSH_PRIVATE_KEY is not set"
            exit 1
          else
            echo "SSH_PRIVATE_KEY is set"
          fi

          # Создадим директорию для ключей, если её нет
          mkdir -p ~/.ssh

          # Запишем ключ в файл
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Проверим, что ключ записан в файл
          ls -la ~/.ssh  # Выводим список файлов в директории
          cat ~/.ssh/id_rsa  # Проверяем содержимое ключа

          # Установим права на ключ
          chmod 600 ~/.ssh/id_rsa

          # Проверим права на id_rsa
          ls -la ~/.ssh

          # Добавим хост в known_hosts
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts

          echo "SSH setup completed"
        
      - name: Debug SSH connection
        run: |
          echo "Trying to SSH to the server..."
          ssh -vvv -o StrictHostKeyChecking=no kawabanga@192.168.0.13 echo "SSH connection successful"
        
      - name: Deploy to server
        run: |
          echo "Deploying to the server..."
          ssh -o StrictHostKeyChecking=no kawabanga@192.168.0.13 << 'EOF'
          cd /c/Users/kawabanga/111
          git pull origin main
          go build -o app .
          pkill -f ./app || true
          nohup ./app &
          EOF
