jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Setup
        run: |
          echo "Starting SSH setup"
          mkdir -p ~/.ssh
          ls -la ~/.ssh  # Проверка папки
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          ls -la ~/.ssh  # Проверка файла id_rsa
          chmod 600 ~/.ssh/id_rsa  # Исправляем права на id_rsa
          ls -la ~/.ssh  # Проверка прав после изменения
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa  # Проверим содержимое приватного ключа
          cat ~/.ssh/known_hosts  # Проверим, что хост добавлен
          echo "SSH setup completed"

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -v kawabanga@192.168.0.13 echo "SSH connection successful"
          
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Исправляем права на id_rsa
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no kawabanga@192.168.0.13 << 'EOF'
          cd /c/Users/kawabanga/111/.github/workflows
          git pull origin main
          go build -o app .
          ./app &
          EOF
