name: SSH Setup and Connect

on:
  push:
    branches:
      - main  # Или другая ветка, на которой нужно запускать

jobs:
  setup-ssh:
    runs-on: ubuntu-latest  # Используем Ubuntu для работы с SSH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "Starting SSH setup..."

          # Создаем папку для SSH, если ее нет
          mkdir -p ~/.ssh
          
          # Проверим, что папка существует
          ls -la ~/.ssh  

          # Запишем приватный ключ в файл (из секрета)
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Проверим, что файл id_rsa появился
          ls -la ~/.ssh  

          # Устанавливаем правильные права доступа на ключ
          chmod 600 ~/.ssh/id_rsa

          # Проверим права на id_rsa
          ls -la ~/.ssh

          # Проверим содержимое приватного ключа (чтобы убедиться, что он правильно записан)
          cat ~/.ssh/id_rsa  

          # Сканируем и добавляем хост в known_hosts, чтобы избежать предупреждения о неизвестном хосте
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts
          
          # Проверим, что хост добавлен в known_hosts
          cat ~/.ssh/known_hosts

          echo "SSH setup completed"

      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection..."
          
          # Используем SSH для подключения к серверу
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kawabanga@192.168.0.13 "echo 'SSH connection successful'"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH Success Message
        run: echo "SSH connection was successful."
