name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Настройка SSH
      - name: Debug SSH setup
        run: |
          echo "Starting SSH setup"
          mkdir -p ~/.ssh
          ls -la ~/.ssh  # Проверим, что папка существует
          
          echo "Printing SSH private key..."
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Создаем файл с ключом
          
          ls -la ~/.ssh  # Проверим, что файл появился
          chmod 600 ~/.ssh/id_rsa  # Исправляем права на id_rsa
          
          ls -la ~/.ssh  # Проверим права файла id_rsa
          cat ~/.ssh/id_rsa  # Проверим содержимое ключа
          
          # Сканируем и добавляем хост
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Проверим, что хост добавлен

          echo "SSH setup completed"

      # Проверка подключения по SSH
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -v kawabanga@192.168.0.13 echo "SSH connection successful"

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Настройка SSH
      - name: Set up SSH for deployment
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Исправляем права на id_rsa
          
          # Добавление хоста
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts

      # Деплой на сервер
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no kawabanga@192.168.0.13 << 'EOF'
          cd /c/Users/kawabanga/111/.github/workflows
          git pull origin main
          go build -o app .
          ./app &
          EOF
