name: SSH Setup and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-ssh-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "Starting SSH setup..."
          
          # Создаем папку для SSH, если ее нет
          mkdir -p ~/.ssh
          
          # Проверим, что папка существует
          ls -la ~/.ssh  

          # Проверим содержимое переменной SSH_PRIVATE_KEY (на всякий случай, осторожно с приватным ключом)
          echo "SSH_PRIVATE_KEY is set: $SSH_PRIVATE_KEY"
          
          # Проверка, что ключ не пустой
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "ERROR: SSH_PRIVATE_KEY is empty"
            exit 1
          else
            echo "SSH_PRIVATE_KEY is successfully passed"
          fi

          # Запишем приватный ключ в файл (из секрета)
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Проверим, что файл id_rsa появился
          ls -la ~/.ssh  

          # Устанавливаем правильные права доступа на ключ
          chmod 600 ~/.ssh/id_rsa

          # Проверим права на id_rsa
          ls -la ~/.ssh

          # Проверим содержимое приватного ключа (чтобы убедиться, что он правильно записан)
          cat ~/.ssh/id_rsa  
          
          # Сканируем и добавляем хост в known_hosts, чтобы избежать предупреждения о неизвестном хосте
          ssh-keyscan -H 192.168.0.13 >> ~/.ssh/known_hosts
          
          # Проверим, что хост добавлен в known_hosts
          cat ~/.ssh/known_hosts

          echo "SSH setup completed"

      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection..."
          # Подключаемся к серверу и выполняем тестовую команду
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa kawabanga@192.168.0.13 "echo 'SSH connection successful'"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          echo "Starting deployment to the server..."
          
          # Пример: Копирование файлов на сервер (например, через SCP)
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./path/to/your/app kawabanga@192.168.0.13:/path/to/remote/deploy/directory

          # Пример: Выполнение команды на сервере для перезапуска приложения
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no kawabanga@192.168.0.13 << EOF
            cd /path/to/remote/deploy/directory
            git pull origin main  # Например, если проект на сервере в git репозитории
            docker-compose up -d  # Если используешь Docker
          EOF

          echo "Deployment completed"

      - name: SSH Success Message
        run: echo "Deployment was successful!"
