name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Проверяем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем зависимости
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    # Запускаем тесты
    - name: Run Tests
      run: go test ./... -v

    # Деплой на сервер
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/my-app
          git pull origin main
          go build -o my-app main.go
          systemctl restart my-app.service
